print("Atendimento SUS")
fila_espera = ("senha 0", "senha 1", "senha 2","senha 3")
total = len(fila_espera)
fila_espera = ("senha 0","senha 1", "senha 2", "senha 3")
print(f"O proximo paciente a ser a atendido é: {fila_espera[0]}")
print(f"O proximo paciente a ser a atendido é: {fila_espera[1]}")
print(f"O proximo paciente a ser a atendido é: {fila_espera[2]}")
print(f"O proximo paciente a ser a atendido é: {fila_espera[3]}")
print(f"Total aguardando: {total}")
